name: Build LLVM with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Asia/Jakarta
  GH_USER: ${{ secrets.GH_USER }}
  GH_EMAIL: ${{ secrets.GH_EMAIL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  LLVM_URL: https://github.com/llvm/llvm-project.git
  DOCKER_IMAGE: mhmmdfdlyas/dockerfile:t-ubuntu
  CONTAINER_NAME: llvm-builder

jobs:
  cloning_task:
    name: Cloning LLVM Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if init.sh exists in GitHub Runner
        run: ls -l ${{ github.workspace }}/tc_scripts/ || echo "init.sh NOT FOUND in Runner!"

      - name: Pull Docker Image
        run: docker pull $DOCKER_IMAGE

      - name: Clone LLVM Project
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            $DOCKER_IMAGE bash -c "
            git clone --single-branch '${LLVM_URL}' -b main /workspace/src/llvm-project --depth=1
          "

  profile_task:
    name: Build LLVM (Profile)
    needs: cloning_task
    runs-on: ubuntu-latest
    steps:
      - name: Start Docker Container
        run: |
          docker run -d --name $CONTAINER_NAME -v ${{ github.workspace }}:/workspace $DOCKER_IMAGE tail -f /dev/null

      - name: Check if init.sh exists inside Docker
        run: docker exec $CONTAINER_NAME ls -l /workspace/tc_scripts/ || echo "init.sh NOT FOUND in Docker!"

      - name: Run Profile Build
        run: |
          docker exec $CONTAINER_NAME bash -c "
            if [ -f /workspace/tc_scripts/init.sh ]; then
              chmod +x /workspace/tc_scripts/init.sh &&
              /workspace/tc_scripts/init.sh profile
            else
              echo 'ERROR: init.sh NOT FOUND!' && exit 1
            fi
          "

      - name: Stop and Remove Container
        run: docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME